name: floating_bubbles
description: A Flutter Package for adding Floating bubbles in the background to a widget.
version: 0.0.1
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  simple_animations:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
